Security Fix for Arbitrary Code Execution - huntr.dev
uber/petastorm pull request #637
Opened 2021-01-21 09:49 UTC by huntr-helper

https://huntr.dev/users/d3m0n-r00t has fixed the Arbitrary Code Execution vulnerability 🔨. Think you could fix a vulnerability like this?

Get involved at https://huntr.dev/

Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/petastorm/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/pip/petastorm/1/README.md

### User Comments:

### 📊 Metadata *
Fixed Arbitrary code execution in ```petastorm```

#### Bounty URL: https://www.huntr.dev/bounties/1-pip-petastorm/

### ⚙️ Description *
```Petastorm``` is an open source data access library developed at Uber ATG. This library enables single machine or distributed training and evaluation of deep learning models directly from datasets in Apache Parquet format. Petastorm supports popular Python-based machine learning (ML) frameworks such as Tensorflow, PyTorch, and PySpark. It can also be used from pure Python code.

```Vulnerability description``` untrusted loading of data by the ```pickle.load``` function leading to ```Arbitrary code execution```.

### 💻 Technical Description *
The function ```depickle_legacy_package_name_compatible()``` blindly loads a pickle file without any validation making it vulnerable to ```Arbitrary Code Execution```. If the input pickle file is a malicious payload,  create a file remotely.
### 🐛 Proof of Concept (PoC) *
```python
import os
import pickle
#os.system('pip3 install petastorm')
from petastorm.etl import legacy
#payload formation
class ArbitraryCode:
    def __reduce__(self):
        cmd = ('xcalc')
        return os.system, (cmd,)
#Exploiting
dumps = pickle.dumps(ArbitraryCode())
legacy.depickle_legacy_package_name_compatible(dumps)
```
![Screenshot 2021-01-05 193250](https://user-images.githubusercontent.com/29670330/103656591-cb518600-4f8e-11eb-83d9-b7edad58a48d.png)

### 🔥 Proof of Fix (PoF) *
![Screenshot 2021-01-05 193940](https://user-images.githubusercontent.com/29670330/103656611-d0163a00-4f8e-11eb-9cd5-642a42fd2835.png)

Fix when subprocess is called.
![Screenshot 2021-01-05 195008](https://user-images.githubusercontent.com/29670330/103656973-487cfb00-4f8f-11eb-85a4-629142af1280.png)

### 👍 User Acceptance Testing (UAT)
Applied fix from pickle official fix as explained in here.
https://www.cmi.ac.in/~madhavan/courses/python-2014/docs/python-3.2.1-docs-html/library/pickle.html
Proper working. (Something other than a payload).
![Screenshot 2021-01-05 195158](https://user-images.githubusercontent.com/29670330/103657187-985bc200-4f8f-11eb-9f61-34647e357142.png)

2021-01-21 09:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/petastorm?pullRequest=637) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/uber/petastorm?pullRequest=637) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: JamieSlome<br/>:x: d3m0n-r00t<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/petastorm?pullRequest=637) it.</sub>

2021-01-21 09:50 UTC, JamieSlome commented
@d3m0n-r00t - are you able to sign the CLA? Cheers! 🍰

2021-01-23 03:46 UTC, selitvin commented
Thanks for the proposed fix. I created #640 which properly fixes the issue in the context of petastorm (this PR would not pass unit tests)

2021-01-29 02:19 UTC, selitvin requested changes

2021-01-29 02:19 UTC, selitvin commented on petastorm/etl/legacy.py
> +    restricted_loads(pickled_string)
We are ignoring the return value here. Also, the implementation fails the tests. Started https://github.com/uber/petastorm/pull/640 to resolve test issues.

2022-04-14 04:41 UTC, selitvin commented
Fixed by #640. Closing this PR.

2022-04-14 04:41 UTC, closed without merging