Support results_queue_size parameter in make_batch_reader api
uber/petastorm pull request #783
Opened 2022-10-29 21:04 UTC by s-udhaya

The default results_queue_size used in make_batch_reader is 50. This will lead to OOM exception while loading big datasets with thread reader pool type. By exposing results_queue_size parameter via make_batch_reader api, the user is able to control the prefetched data size which in turns will help to alleviate OOM issue.

2022-10-29 21:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/petastorm?pullRequest=783) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/petastorm?pullRequest=783) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/petastorm?pullRequest=783) it.</sub>

2022-10-29 21:09 UTC, s-udhaya commented
@selitvin I am in the process of making end to end DDL demos with big datasets, petastorm and horovod + DDP strategies. Many thanks for the great library. I encountered OOM issue during the process and this fix will help me to alleviate that issue. Could you please have a look at it whenever you have time?

2022-11-01 15:45 UTC, selitvin requested changes
Awesome improvement - thank you!

Minor ask:

If possible, I'd like to ask you to add a unittest (I guess just peak into the member variable of the queue?) to see if the queue size propagated properly. Should be pretty straight forward (can put it in `tests/test_parquet_reader.py`?)
Also, please add a line into `docs/release-notes.rst` describing the change.

Thank you!

2022-11-05 06:29 UTC, s-udhaya commented
@selitvin Many thanks for the review. I will update the PR with your suggestions.

2022-11-26 13:02 UTC, s-udhaya commented
@selitvin It took a while for me to update the PR 😃 Please have a look at it whenever you have time. Thanks

2022-11-29 00:02 UTC, selitvin approved these changes
LGTM

2022-11-30 16:55 UTC, selitvin approved these changes

2022-12-07 20:42 UTC, s-udhaya commented
@selitvin Thanks for the approval. What is the process now to get this PR to be merged onto the main?

2022-12-13 01:19 UTC, merged

2022-12-13 01:19 UTC, selitvin commented
Merged. I need to cut a release now that will include your change.

2022-12-13 01:30 UTC, selitvin commented
I am pushing a release candidate v0.12.1rc0 now. Will release tomorrow.